# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C5ItemModel',
            fields=[
                ('price', models.CharField(max_length=20, null=True)),
                ('decoration_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('decoration_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_url', models.CharField(max_length=50)),
            ],
        ),
    ]
