# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamSpider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c5itemmodel',
            name='item_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
