# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImbaSteamItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=45)),
                ('rarity', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('tags', models.CharField(blank=True, max_length=512, null=True)),
                ('ban', models.CharField(max_length=10)),
                ('hero', models.CharField(max_length=45)),
                ('exterior', models.CharField(blank=True, max_length=45, null=True)),
                ('weight', models.SmallIntegerField()),
                ('tradable', models.SmallIntegerField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.IntegerField()),
                ('update_time', models.IntegerField()),
                ('custom_price', models.IntegerField(blank=True, null=True)),
                ('market_hash_name', models.CharField(max_length=255)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('game', models.CharField(blank=True, max_length=50, null=True)),
                ('cardborder', models.CharField(blank=True, max_length=50, null=True)),
                ('item_class', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_num', models.IntegerField()),
                ('rmb_price', models.IntegerField()),
                ('compensate_price', models.IntegerField()),
            ],
            options={
                'db_table': 'imba_steam_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImbaSteamItemPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priceDate', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.ImbaSteamItem')),
            ],
        ),
    ]
